---
title: "COVID-19"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
---

> COVID-19 STATISTICS IN KENYA AS OF `r Sys.Date()`

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(styler)
library(shiny)
library(rvest)
library(lubridate)
```


```{r echo=FALSE, include=FALSE}
covid <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv") 
covid_kenya <- covid%>% 
  filter(location=="Kenya") %>% 
  select(
    -c(1:3,
       contains(
         c("per_million","smoothed", "per_thousand")
         )
       )
    )



str(covid_kenya)

cases <- covid_kenya %>% 
  select(date,contains("cases"))

 cases <-  cases[complete.cases(cases),]

 
deaths <- covid_kenya %>% 
  select(date,contains("deaths"))

deaths <-  deaths[complete.cases(deaths),]

vaccination <- covid_kenya %>% 
  select(date, contains("vaccin"))

vaccination <- vaccination[!is.na(vaccination$people_vaccinated),]
```

Row
----------------------------------------------------------------


### DAY

```{r}
valueBox(Sys.Date())
```



### KENYA TOTAL CASES

```{r}
valueBox(cases[nrow(cases),]$total_cases, icon ="fa-heart", color = "#fa9507" )
```





### KENYA TOTAL DEATHS
```{r}
valueBox(deaths[nrow(deaths),]$total_deaths, icon ="fa-heartbeat", color = "#e60505" )
```


### KENYA VACCINATION

```{r}

valueBox(vaccination[nrow(vaccination),]$people_vaccinated, icon ="fa-heart", color = "green" )
```



Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

###  NEW CASES

```{r new_cases, fig.cap="New cases per country"}

 cases %>% 
  ggplot(aes(x=date))+
  geom_line(aes(y=new_cases))+
  scale_x_date()+
  scale_y_continuous()
```

### TOTAL CASES

```{r total_cases, fig.cap="Total cases per Country"}
cases%>% 
  #group_by(cases) %>% 
  ggplot(aes(x=date))+
  geom_line(aes(y=total_cases/1000))+
  scale_x_date()+
  scale_y_continuous()+
  labs(title = "total cases in thousands(1000)", y="cases")
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

###  DEATH CASES

```{r death_cases, fig.cap="Daily Death cases"}

deaths%>% 
  #group_by(cases) %>% 
  ggplot(aes(x=date))+
  geom_line(aes(y=new_deaths))+
  scale_x_date()+
  scale_y_continuous()
```

### TOTAL CASES

```{r total_death_cases, fig.cap="Total Death cases In the country"}
deaths%>% 
  ggplot(aes(x=date))+
  geom_line(aes(y=total_deaths))+
  scale_x_date()+
  scale_y_continuous()
```






Column {data-height=600}
-----------------------------------------------------------------------
### VACCINATION

```{r}
vaccination %>% 
    ggplot(aes(x=date))+
  geom_point(aes(y=people_vaccinated))+
  geom_line(aes(y=people_vaccinated))+
  scale_x_date()
```
